# Generated by Django 5.0.1 on 2024-01-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_related_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_after_transaction',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
