# Generated by Django 5.0.1 on 2024-01-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_alter_transaction_balance_after_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='related_account',
        ),
    ]
